// AUTO-GENERATED by scripts/snapshot-projects.mjs — do not edit by hand.
// Regenerate with `npm run snapshot` (also runs as part of `npm run build`).
//
// A build-time copy of the `projects` collection, used to paint the home grid
// immediately. Firestore is still the source of truth and overwrites this once
// the live read lands.

import type { Project } from "../types/project";

export const PROJECTS_SNAPSHOT: Project[] = [
  {
    "id": "1785288163186",
    "eyebrow": "Three.js, Web App",
    "header": "Libre3D",
    "subtitle": "Open-Source alternative to Spline designed for the Agency at UF creative team",
    "coverUrl": "/assets/compressed/Libre3D/Libre3D-Cover.webp",
    "order": 0,
    "color1": "#111627",
    "color2": "#2094C5",
    "color3": "#4f8cff",
    "color4": "#2d5eb0"
  },
  {
    "id": "1782961131323",
    "eyebrow": "React, Web App",
    "header": "New Business Case Studies",
    "subtitle": "The Agency at University of Florida",
    "coverUrl": "/assets/compressed/NewBusiness/heroSection.mp4",
    "order": 1,
    "color1": "#5301d7",
    "color2": "#aa9aff",
    "color3": "#c4b9f8",
    "color4": "#000000"
  },
  {
    "id": "1777141672057",
    "eyebrow": "Figma, Design & Interactive Protoype",
    "header": "LockedIn",
    "subtitle": "A study spot finder for students at the University of Florida",
    "coverUrl": "/assets/compressed/LockedIn/LockedInCover.webp",
    "order": 2,
    "color1": "#eb8e4b",
    "color2": "#ffc670",
    "color3": "#ffe3bd",
    "color4": "#fffbed"
  },
  {
    "id": "1769497710828",
    "eyebrow": "Unity, VR",
    "header": "VR: Classroom",
    "subtitle": "Exposure Therapy Simulation for Students with Sensory Disorders",
    "coverUrl": "/assets/compressed/VRClassroom/VR-Classroom-Cover.webp",
    "order": 3,
    "color1": "#1b2b41",
    "color2": "#a28f6e",
    "color3": "#693e30",
    "color4": "#696969"
  },
  {
    "id": "1769542388823",
    "eyebrow": "React, Web App",
    "header": "Sociopolis",
    "subtitle": "Gamified Sociology Learning App  ",
    "coverUrl": "/assets/compressed/Sociopolis/Sociopolis-Cover.webp",
    "order": 5,
    "color1": "#283d52",
    "color2": "#6297cb",
    "color3": "#cee3f8",
    "color4": "#c3ae73"
  },
  {
    "id": "1769547665588",
    "eyebrow": "React, Web App",
    "header": "Jukebox, Open Source Club",
    "subtitle": "A web application that allows group members to queue up songs to their group’s playlist.",
    "coverUrl": "/assets/compressed/Jukebox/Jukebox-OpenSource-Cover.webp",
    "order": 6,
    "color1": "#05060a",
    "color2": "#2094C5",
    "color3": "#b4532a",
    "color4": "#d7c8a2"
  }
];

export const SNAPSHOT_GENERATED_AT = "2026-08-22T03:09:56.925Z";
